name: Auto Deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: skip or not
        id: skipornot
        uses: fcurella/gh-action-commit-msg@main
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        if: ${{ !contains(steps.skipornot.outputs.message, 'skip ci') }}
        uses: "fcurella/gh-status-check@main"
        with:
          ignoreContexts: coverage/coveralls
          checkInterval: 12
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'placeholder'
        run: "echo hurray"
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LABELS: release
